/**
 * Fork update channel: swap-style installer for adhoc-signed macOS builds.
 *
 * Squirrel.Mac refuses to install into an app that has no real code
 * signature, which is exactly what the local builds are. So instead of
 * quitting into Squirrel we do the swap ourselves:
 *
 *   1. ditto-extract the downloaded zip into userData (same volume as the
 *      target on this machine, but the copy below works cross-volume too);
 *   2. verify the staged bundle is really this application — same bundle
 *      identifier — so a fork build can never be replaced by someone else's
 *      app (the reason upstream's channel was disabled in the first place);
 *   3. hand a self-contained bash script to a detached process and exit.
 *      The script waits for this process to die, moves the running bundle
 *      aside, puts the new one in place, relaunches it, and rolls back if
 *      the copy fails.
 *
 * User data lives outside the bundle (~/Library/Application Support/...),
 * so replacing the .app loses nothing.
 *
 * This module is Electron-free on purpose: every piece is unit-testable.
 */
import { execFile as execFileCallback } from 'node:child_process'
import { chmodSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { promisify } from 'node:util'

import { pendingUpdateRoot } from './fork-update-download'

const execFile = promisify(execFileCallback)

/** `/Applications/Foo.app/Contents/Resources/app` → `/Applications/Foo.app`. */
export function appBundlePathFromAppPath(appPath: string): string {
  const marker = '.app/'
  const index = appPath.indexOf(marker)
  if (index >= 0) return appPath.slice(0, index + marker.length - 1)
  return appPath
}

export function readBundleIdentifier(appBundlePath: string): string | undefined {
  try {
    const plist = readFileSync(join(appBundlePath, 'Contents', 'Info.plist'), 'utf8')
    const match = plist.match(/<key>CFBundleIdentifier<\/key>\s*<string>([^<]+)<\/string>/)
    return match?.[1]
  } catch {
    return undefined
  }
}

/** Extract the update zip and locate the .app it contains. */
export async function stageForkUpdate(
  zipPath: string,
  version: string,
  userDataPath: string
): Promise<string> {
  const staging = join(pendingUpdateRoot(userDataPath), `staged-${version}`)
  mkdirSync(staging, { recursive: true })
  await execFile('/usr/bin/ditto', ['-x', '-k', zipPath, staging])
  const bundle = readdirSync(staging).find((entry) => entry.endsWith('.app'))
  if (!bundle) {
    throw new Error('更新包中没有找到 .app')
  }
  return join(staging, bundle)
}

export interface SwapPlan {
  /** PID of the running app; the script waits for it to exit. */
  pid: number
  /** Absolute path of the installed bundle being replaced. */
  currentAppPath: string
  /** Absolute path of the extracted new bundle. */
  stagedAppPath: string
  /** Where the current bundle is parked for rollback. */
  backupPath: string
  /** Swap progress log, outside pending-update so cleanup keeps it. */
  logPath: string
}

export function backupPathFor(currentAppPath: string, oldVersion: string): string {
  return `${currentAppPath}.fork-backup-${oldVersion}`
}

/** Sibling entries left behind by earlier swaps, for the manager to trash. */
export function findUpdateBackups(currentAppPath: string): string[] {
  try {
    const name = currentAppPath.split('/').pop() ?? ''
    return readdirSync(dirname(currentAppPath))
      .filter((entry) => entry.startsWith(`${name}.fork-backup-`))
      .map((entry) => join(dirname(currentAppPath), entry))
  } catch {
    return []
  }
}

function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

export function generateSwapScript(plan: SwapPlan): string {
  return `#!/bin/bash
# Generated by the DSH Desktop fork updater for a single swap. Self-contained.
set -u
LOG=${shq(plan.logPath)}
PID=${plan.pid}
CURRENT=${shq(plan.currentAppPath)}
STAGED=${shq(plan.stagedAppPath)}
BACKUP=${shq(plan.backupPath)}

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $*" >> "$LOG"; }

log "waiting for pid $PID to exit"
for _ in $(seq 1 240); do
  kill -0 "$PID" 2>/dev/null || break
  sleep 0.5
done
if kill -0 "$PID" 2>/dev/null; then
  log "app did not exit within 120s, aborting"
  exit 1
fi

log "moving current app aside: $CURRENT"
rm -rf "$BACKUP"
if ! mv "$CURRENT" "$BACKUP"; then
  log "could not move current app aside, leaving everything untouched"
  exit 1
fi

if /usr/bin/ditto "$STAGED" "$CURRENT" >> "$LOG" 2>&1; then
  /usr/bin/xattr -dr com.apple.quarantine "$CURRENT" 2>/dev/null
  log "relaunching updated app"
  open "$CURRENT"
  rm -rf "$(dirname "$STAGED")"
  rm -f "$0"
else
  log "copy failed, rolling back"
  rm -rf "$CURRENT"
  mv "$BACKUP" "$CURRENT"
  log "rolled back to the previous build"
  exit 1
fi
`
}

/** Write the swap script next to the staged bundle and make it executable. */
export function writeSwapScript(plan: SwapPlan): string {
  const scriptPath = join(pendingUpdateRootFromStaged(plan.stagedAppPath), `swap-${plan.pid}.sh`)
  mkdirSync(dirname(scriptPath), { recursive: true })
  writeFileSync(scriptPath, generateSwapScript(plan), 'utf8')
  chmodSync(scriptPath, 0o755)
  return scriptPath
}

function pendingUpdateRootFromStaged(stagedAppPath: string): string {
  // stagedAppPath = <root>/staged-<version>/<Name>.app
  return dirname(dirname(stagedAppPath))
}
